### PR TITLE
Add function to create a new titled section

### PR DESCRIPTION
**Pull request by jonasj76**
Example included.

### CODE REVIEW

**Comment by troglobit** [comment]
Great stuff, Jonas!  Could you perhaps also add a unit test (see `tests/`) for this?

**Comment by peda-r** [comment]
I have been using:
`char tmp[large_enough];`
`sprintf(tmp, "section-name \"%s\" {\n}", title);`
`cfg_parse_buf(cfg, tmp);`

Which is kind of ugly...

**Comment by peda-r** [comment]
Hmm, I think attempts to *add* a pre-existing section should fail.
Maybe add a flags argument to get selective behavior?

**Comment by troglobit** [comment]
@peda-r Yeah this is cleaner.

Hmm, you're right and it also touches upon a related problem of mine. A global `CFGF_OVERWRITE` flag could control overwriting anything, good idea!

**Comment by peda-r** [comment]
I was thinking a flags argument to the new function, but I guess I don't care deeply about where the flags are specified...

**Comment by troglobit** [comment]
I just zoomed out a bit: a user that wants to add a section likely also want to be able to add other things as well.

**Comment by jonasj76** [comment]
Unit test added.
I agree that the default for adding a pre-existing section should fail. But should it be a flag or not to override this behaviour?

**Comment by troglobit** [comment]
@jonasj76 Thanks! :)

Yeah I think we should have a global flag, like this:

    if (cfg->flags & CFGF_IGNORE_UNKNOWN)
        clear_current_opt()
    if (set_value() fails)
         errno = EEXIST;
         return NULL;

or something, but I guess it could also be an option flag. I don't have a strong opinion on either one.  With a global flag we could let it cascade down on all options on cfg_init() so the code only needs to check `opt->flags` ...

**Comment by jonasj76** [comment]
Added commit to fail when adding a pre-existing section.

**Comment by troglobit** [comment]
Awesome, thanks! 

Like we discussed AFK today, adding a global and/or per-setting CFGF_OVERWRITE can be added later.

**Pull request merged**
