### PR TITLE
Add support for Travis-CI and Coverity Scan

### PR DESCRIPTION
**Pull request by troglobit**
This patch set adds support for Travis-CI, automatic builds at checkin,
and Coverity Scan for static code analysis.  It also contains a refactor
of the autogen.sh script to rely on autoreconf instead of calling each
autotool manually.

### CODE REVIEW

**Comment by DavidEGrayson** [comment]
You added some weird stuff to line 1 of README.me, but otherwise this looks okay.

By the way, I find it odd that `autogen.sh` calls `configure`.  It made it hard to do out-of-tree builds from the git repository.

**Comment by troglobit** [comment]
The weird stuff is for displaying neat icons with clickable status.

Yeah, I've been thinking about removing the configure line. All it really does is enable maintainer mode, doesn't really seem necessary.  I'll update the PR with that line removed.  We can run
autoreconf with the `-m` switch instead. That will cause it to call configure + make if there was a previous build. (I think it looks for config.log to detect this.)

**Comment by DavidEGrayson** [comment]
Ok, I no longer see the weird stuff on line 1 of README.md.  Maybe it was a GitHub glitch.

**Comment by troglobit** [comment]
Naw, I updated the PR :)

**Pull request merged**
