### PR TITLE
Msvc autotools

### PR DESCRIPTION
**Pull request by peda-r**
Ok, with all the talk about AppVeyor/MSYS2 I decided to try to build libconfuse using the original MSYS (which I have installed, I don't have MSYS2) and MSVC 2010. I bumped into a number of difficulties, all of which I have solved in this branch. Except one, namely the C99 initializers from when the simple option union was introduced (57b9738acd5dd976bac95270885ec3532b18b553). I reverted that commit on top of this branch and I was able to build with my old tools like this:

Open a MSVC 2010 command shell, and launch MSYS from it. From within the MSYS shell, do
`.../configure --disable-examples CC=cl CFLAGS=-MD RANLIB=: NM="dumpbin -symbols" AR=lib`
`make`
`make check`

Everything passes. I think the C99 initializers are supported by newer MSVC, so that particular problem will solve itself over time. Other than that, for projects that I maintain, I detest multiple build systems. Therefore, I very much favor supporting MSVC through autotools instead of project files that always ends up lagging behind.

However, that puts Windows user in a position where they have to install MSYS. But the patches in this branch doesn't look all that nasty, most of them just shows that building with older MSVC hasn't been done in a while. Has anybody built with newer MSVC recently? And these patches doesn't stop anyone from keeping maintaining the windows project files...

Anyway, it should be possible to add a build with MSYS/MSVC on AppVeyor. But someone has to verify that the work I put into automake/libtool to support MSYS/MSVC a couple of years ago works with MSYS2 as well, I can't really see why it would fail, but I wouldn't be surprised if there is some quirk to figure out...

Cheers,
Peter

### CODE REVIEW

**Comment by troglobit** [comment]
Looks great, good work mate!

**Comment by peda-r** [comment]
Hmm, I just realized that there's one unintended change in there.

I changed ssize_t to size_t in aa210eb and forgot about it and didn't mention it in the commit msg. That may have to be fixed in some other way or there might be problems on other toolchains.

Have to catch some sleep now though...

Cheers,
Peter

**Comment by DavidEGrayson** [comment]
In case it's helpful to you, I was able to build libconfuse in Visual Studio 2015 Community Edition with the changes on this branch: https://github.com/DavidEGrayson/libconfuse/tree/vs2  I was going to make a pull request but decided I that I cared about MSYS2 more so I would work on that instead.

Support for C99 has increased in recent versions of Visual Studio; I didn't need to move all the variable definitions to the beginning of a block like you are doing.

**Comment by DavidEGrayson** [comment]
Another option is to use CMake: it can generate MSYS/MSYS2 Makefiles, or it can generate Visual Studio project files.

**Comment by peda-r** [comment]
Ok, I fixed the ssize_t vs size_t thing in a cleaner way.

Regarding the vs2 branch, I think it neatly sums up why I don't like to keep MS project files in the source tree. When MS ships a new version, you have to replace the whole content, and you lose support for the older compiler. Or you have yet another project file to keep up to date. It's simply not maintainable in the long run. CMake is better I suppose, but if the project is already using autotools, it might be a hard sell to get the team to switch or support both autotools and CMake. Especially when you can build for MSVC using the autotools build system. But I wouldn't be maintaining the MSVC project files, and have never used CMake, and I don't run this project, so my opinion doesn't really matter...

Now I really need to get some sleep.

Cheers,
Peter

**Comment by troglobit** [comment]
I would love pull this, but @DavidEGrayson is right, the `ssize_t` thing needs fixing.  However broken it may be originally in libConfuse.  

Just looked at the current code and in my libC `strlen()` returns `size_t` and `malloc()` takes `size_t` as an input argument. Very confusing that libConfuse currently casts it to an `ssize_t`, so I fixed it.  Sorry for stealing your thunder on this one guys!

**Comment by troglobit** [comment]
Also, I'm not a huge fan of CMake, but I also don't really llike autotools ... if I had my way we'd all be using plain Makefiles :smirk: 

However, for the sake of the project I don't really have a strong opinion, either way. Even though an autotools2cmake PR would have to go through some gigantic hoops to be merged ... mostly because I'd have to read up on it massively again to be able to work with it.

**Comment by peda-r** [comment]
Right, that #define ssize_t size_t is brain damaged and will probably lead to mysterious bugs down the line. I'll rebase the branch on top of the patch just pushed by @troglobit

**Comment by peda-r** [comment]
Done.

**Comment by DavidEGrayson** [comment]
If this project is committing to support Visual Studio 2010, I'd probably say that in the documentation.  But personally I would have picked a newer version that has better C99 support so that you don't need to make quite so many changes.

**Comment by peda-r** [comment]
Since MSVC 2010 doesn't have C99 initializers anyway, I'm fine with dropping the snprintf patch (but that breaks 2012 and 2013 as well, I think?). The rest of the patches are very small and harmless.

Which of the other patches are candidates for dropping with newer MS compilers?

**Comment by troglobit** [comment]
My main concern with this PR was just the duplicated #ifdefs for snprintf(), which maybe could've been stowed away as static inline in some shared header.  Other than that my impression was good general cleanups, in particular moving declarations to the top of functions which is not only a compiler thing but also a matter of style.

**Comment by DavidEGrayson** [comment]
I thought that commit 10cbe54ee9733e4d4b5d76643f79ba45ba9b7eb0 (vsnprintf and snprintf wrappers) would not be needed if we used newer versions of Visual Studio, but then I remembered that Microsoft's vsnprintf and snprintf implementations have the wrong return value.

In Visual Studio, [vsnprintf](https://msdn.microsoft.com/en-us/library/1kt27hek.aspx) returns -1 if the number of characters it wants to write is greater than the count.  Similarly, [sprintf](https://msdn.microsoft.com/en-us/library/2ts7cx93.aspx) returns  "negative value" in that case.  These functions are really supposed to return the actual number of characters that would have been written, and the assertion in cfg_make_fullpath relies on that fact.  So maybe commit 10cbe54ee9733e4d4b5d76643f79ba45ba9b7eb0  should be fixed to apply to all versions of MSVC, not just older ones.

Alternatively, if the assertion is fixed to be something like `assert(np >= 0 && np < len);` then we don't care which behavior of snprintf is used.  Then if we drop support for older versions of Visual Studio that don't have vsnprintf and snprintf, we don't need the wrapper functions at all.

I also thought that 7bcade90ec4bad245c2e4a832c27570fa2738dc1 (separating declarations from code) is not needed, but apparently you want to do that regardless of whether it's needed for Visual Studio, and that's fine.

**Comment by troglobit** [comment]
I have no opinion what version of Visual Studio to support, similar to how I don't care what version of GCC or other compiler is used, unless they are severely broken, like GCC 2.96 that RedHat shipped 10+ years ago ... so wrapping *snprintf() in whatever fashion is fine with me.  I'd just like to see those OS/compiler specific wrappers being tucked away somewhere so they don't clutter up the main code.

**Comment by DavidEGrayson** [comment]
@peda-r:  I should admit that I don't fully understand commit 10cbe54ee9733e4d4b5d76643f79ba45ba9b7eb0.  I'm not sure if you are trying to fix the return value of those functions or trying to make those functions work in versions of Visual Studio that don't support them at all.  And I'm not sure why the wrappers aren't defined for _MSC_VER >= 1900.  The documentation says that those functions exist all the way back to Visual Studio 2010, so I guess you just want to fix the return value.  But if you want to fix the return value, I don't know why you have the condition `_MSC_VER < 1900`.

**Comment by peda-r** [comment]
I'm indeed fixing the return value, the reason for _MSC_VER >= 1900 is info from this blog-post:

http://blogs.msdn.com/b/vcblog/archive/2014/06/18/crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1.aspx

Specifically:

> snprintf and vsnprintf Are Now Implemented: The C99 snprintf and vsnprintf functions have been implemented.

So, yes, _vsnprintf_s exist for the new compiler too, but the wrappers should not be needed. Haven't tested though, no MSVC 2015 here. Not yet at least...

**Comment by peda-r** [comment]
Ok, I moved the snprintf wrappers to a new file.

**Comment by DavidEGrayson** [comment]
Okay, I see.  The [vsnprintf documentation for VS2015](https://msdn.microsoft.com/en-us/library/1kt27hek(v=vs.140).aspx) contradicts the information in that [blog post](http://blogs.msdn.com/b/vcblog/archive/2014/06/18/crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1.aspx).  I have VS2015 community edition installed so I will probably test this soon.

**Comment by troglobit** [comment]
Awesome, thanks @peda-r :+1: 

Seems we're ready to merge, huh? :smiley:

**Comment by peda-r** [comment]
Yeah, I guess that's expected, the blog post has this gem:

> Please note that the documentation on MSDN has not yet been updated to include any of the changes covered in these blog posts.

**Comment by peda-r** [comment]
Merge ok by me, obviously... :-)

**Comment by troglobit** [comment]
Great read, this thread.  Kinda makes me miss a ★ on posts ... like Twitter ;)

**Comment by DavidEGrayson** [comment]
Oh, the pull request now contains a new license.  Does that license apply to binary copies of the software?  If so, it will be easier on us packagers if Peter can copy his copyright statement into the top-level LICENSE.

**Comment by peda-r** [comment]
I just copied the confuse.h license. I claim nothing and will put whatever you like as a license on that file. I just don't care, but Martin didn't have anything to do with the file, so putting his name there would have been actively wrong. I also hear that public domain is also troublesome in some jurisdictions, so I had to put something there.

Your call, guys.

**Comment by troglobit** [comment]
@DavidEGrayson wut now, what license?  The new `compat.h` has the same ISC license as the top level LICENSE file.

**Comment by DavidEGrayson** [comment]
Yes, I meant the copyright with Peter's name, and the license that says the copyright must be included in distributions.

**Comment by peda-r** [comment]
I have now read that MSDN snprintf page @DavidEGrayson linked to, and that made me think that we should probably check if MSDN is as buggy as it usually is before the merge. No?

**Comment by peda-r** [comment]
I mean, MSDN specifically states that snprintf is the same as _snprintf. MSDN isn't usually that bad, is it?

> vsnprintf is identical to _vsnprintf. vsnprintf is included for compliance to the ANSI standard; _vnsprintf is retained for backward compatibility.

**Comment by DavidEGrayson** [comment]
It's quite possible that the author of the blog post did not read the C99 specification and think about whether the new vsnprintf and snprintf have the right return values.

**Comment by troglobit** [comment]
IANL but the Linux kernel, BusyBox and others not part of the GNU project successfully distribute free/libre/open source software with copyright assigned to individuals.  I personally see no problem with this, as do many others from what I've read earlier.  The ISC license itself is extremely liberal, the OpenBSD (known for their particularly liberal stance) switched early in their project from the 3-clause BSD license to ISC to be even more liberal.

However, maybe we should at the very least update the top-level LICENSE file in cases like this, i.e.
add a `Copyright (c) 2015  Peter Rosin <peda@lysator.liu.se>`, it wouldn't hurt.

@DavidEGrayson in any event, if you are unsure about including open source software in your own works you should always get legal counsel.

**Comment by troglobit** [comment]
As for the compat issues, I say merge and fix later if there is any problem.

**Comment by peda-r** [comment]
Hmm, but it says ANSI, not C99, and the text is the same for 2010, so they probably refer to the usual OLDNAMES.LIB compatibility junk. Ok, goferit.

**Comment by DavidEGrayson** [comment]
Yeah, I'm in favor of updating the top-level LICENSE with Peter's copyright.

**Comment by troglobit** [comment]
OK, @peda-r update the LICENSE file (as I mentioned above) in the commit you add compat.h, then I'll merge! :+1:

**Comment by DavidEGrayson** [comment]
Looks good, thanks everyone!

**Comment by troglobit** [comment]
Great work everyone, and awesome discussions :+1: 

Thank you again @peda-r for contributing to libConfuse! <3

**Comment by peda-r** [comment]
And thanks to you too, for feedback etc etc yada yada :-)

**Comment by DavidEGrayson** [comment]
I tested snprintf in Visual Studio 2015 Community Edition and its return value is correct when there is an overflow.  :+1:

**Comment by DavidEGrayson** [comment]
But _snprintf returns -1 if there is an overflow in VS2015.  I think my earlier comments today overlooked the fact that snprintf is different from _snprintf and vsnprintf is different from _vsnprintf.  Sorry for the confusion.

**Comment by troglobit** [comment]
@DavidEGrayson no problem, thank you for testing! :smiley:

**Pull request merged**
