### PR TITLE
check for missed closing braces at the end of the parsing

### PR DESCRIPTION
**Pull request by furmur**

### CODE REVIEW

**Comment by troglobit** [comment]
Seems like a good idea. Waiting for some more people to chime in on it before merging.

**Comment by dmitry-sinina** [comment]
any update?

**Comment by troglobit** [comment]
Grace period passed, merging.

**Comment by troglobit** [comment]
Reverting this on master, even the most obvious tests are not passing anymore.  The check is relevant, but is malplaced since the parser is recursive and EOF is received when at least one or more levels down.

**Pull request merged**
